export const USER_REQUESTING_PROFILE = 'USER_REQUESTING_PROFILE';
export const USER_IS_NOT_LOGGED_IN = 'USER_IS_NOT_LOGGED_IN';
export const USER_RECEIVED_PROFILE = 'USER_RECEIVED_PROFILE';
export const USER_UPDATING_PROFILE = 'USER_UPDATING_PROFILE';
export const USER_UPDATED_PROFILE = 'USER_UPDATED_PROFILE';
export const USER_UPDATE_PROFILE_FAILED = 'USER_UPDATE_PROFILE_FAILED';
